### ISSUE TITLE
Token 希望变成可选参数

### ISSUE THREAD

**Issue by x-cold** [atian25/node-yuque#10]
用户的知识库就是公开的情况下

- 不需要使用 token 进行数据获取的鉴权；
- 如果是在开源项目中使用 yuque 的 api，也不希望在源码中有所暴露；
- 团队协作使用同一个 token 可能造成信息泄露

**Comment by atian25** [comment]
1. 没有 TOKEN 的，一小时请求才 200 次。 https://www.yuque.com/yuque/developer/api#5b3a1535
2. 开源项目的单测可以通过 travis env 的方式去注入
3. 你可以通过 [dotenv](https://www.npmjs.com/package/dotenv) 的方式，读取本地的文件来注入 env，然后这个文件不要加到 git 去。
