### ISSUE TITLE
How about @yuque/sdk ?

### ISSUE THREAD

**Issue by int64ago** [atian25/node-yuque#5]
I'll transfer `yuque` org to you if you need.

**Comment by atian25** [comment]
sure, cool~ thanks~ my npm account is `atian25`

**Comment by int64ago** [comment]
@atian25 Done! You can now remove me from the org :-)

**Comment by atian25** [comment]
thanks~

**Comment by atian25** [comment]
and this repo will transfer to https://github.com/yuque

**Comment by int64ago** [comment]
Looks awesome!

**Comment by atian25** [comment]
https://www.npmjs.com/package/@yuque/sdk

![image](https://user-images.githubusercontent.com/227713/55930969-466cf780-5c56-11e9-8197-bf2ef016919d.png)
